create table tg_user (
    id bigint primary key,
    user_name varchar(100) not null unique,
    first_name varchar(100),
    chat_id bigint not null default 0,
    is_subscribed  boolean default false
);

create table user_choice_data (
    id int generated by default as identity primary key,
    user_id bigint references tg_user(id) on delete restrict,
    genre varchar(50),
    year varchar(30),
    rating varchar(4)
);

create table movie (
    id int primary key,
    name varchar,
    alternative_name varchar,
    year varchar,
    description varchar
);

create table user_movie (
    tg_user_id bigint references tg_user(id),
    movie_id int references movie(id),
    added_at timestamp,
    is_watched boolean default false,
    user_rating int check(user_rating between 0 and 10),
    primary key(tg_user_id, movie_id)
);


-- Старая версия
create table movie (
                       id int primary key,
                       name varchar,
                       alternative_name varchar,
                       year varchar,
                       description varchar,
                       added_by_user_id bigint references tg_user(id) on delete restrict,
                       added_at timestamp,
                       is_watched boolean,
                       user_rating int check (user_rating >= 0)
);