meta:
  environment: jvm
  toolchain:
    name: maven
    version: 17
build:
  artifacts:
    target/*.jar: /
  args: 'spring-boot:repackage '
run:
  jarName: target/movie2watch-telegram-bot.jar
  persistence_mount: /data
  container_port: 80
